<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <title>Kết quả đánh giá trầm cảm</title>

    <!-- Thư viện SweetAlert và html2pdf -->
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>

    <style>
    #pdf-content {
        display: none;
        padding: 20px;
        font-family: 'Arial', sans-serif;
    }

    #pdf-content h1 {
        text-align: center;
        color: #2C3E50;
    }

    #pdf-content ul {
        list-style-type: none;
        padding-left: 0;
    }

    #pdf-content li {
        margin-bottom: 10px;
    }

    #pdf-content p.footer {
        margin-top: 30px;
        text-align: center;
        font-size: 12px;
        color: gray;
    }
    </style>
</head>

<body>

    <script>
    // Mock dữ liệu
    const questions = [
        "Tôi cảm thấy buồn bã nhiều ngày.",
        "Tôi mất ngủ hoặc ngủ quá nhiều.",
        "Tôi cảm thấy tuyệt vọng.",
        "Tôi khó tập trung vào công việc.",
        "Tôi ăn ít hơn bình thường hoặc ăn quá nhiều."
    ];

    const answers = [2, 1, 0, 2, 1]; // điểm cho từng câu, user chọn

    // Hàm tính kết quả
    function calculateResult() {
        const totalScore = answers.reduce((sum, score) => sum + (score || 0), 0);
        let resultMessage = '';

        if (totalScore <= 10) {
            resultMessage = "Bạn không có dấu hiệu trầm cảm.";
        } else if (totalScore <= 18) {
            resultMessage = "Bạn có thể đang bị trầm cảm nhẹ.";
        } else if (totalScore <= 29) {
            resultMessage = "Bạn có thể đang bị trầm cảm vừa. Hãy cân nhắc gặp chuyên gia tâm lý.";
        } else {
            resultMessage = "Bạn có thể đang bị trầm cảm nặng. Hãy tìm sự giúp đỡ từ chuyên gia ngay lập tức.";
        }

        // Đổ nội dung ra div PDF ẩn
        generatePDFContent(totalScore, resultMessage);

        // Hiện thông báo
        swal({
            title: "Kết quả đánh giá",
            text: `Điểm số của bạn: ${totalScore}\n${resultMessage}`,
            icon: "success",
            buttons: {
                cancel: {
                    text: "Thoát",
                    visible: true,
                    className: "btn btn-danger"
                },
                confirm: {
                    text: "Quay lại",
                    className: "btn btn-primary"
                },
                download: {
                    text: "Xuất PDF",
                    value: "download",
                    className: "btn btn-success"
                }
            }
        }).then((value) => {
            if (value === true) {
                window.location.href = '../views/test.php';
            } else if (value === "download") {
                exportPDF();
            }
        });
    }

    // Hàm dựng nội dung cho PDF
    function generatePDFContent(score, message) {
        const pdfDiv = document.getElementById('pdf-content');
        pdfDiv.innerHTML = `
            <h1>Kết quả bài test đánh giá trầm cảm</h1>
            <p><strong>Điểm số của bạn:</strong> ${score}</p>

            <h2 style="color: #3498DB;">Chi tiết câu trả lời:</h2>
            <ul>
                ${questions.map((q, index) => `
                    <li><strong>Câu ${index + 1}:</strong> ${q} → <em>Điểm: ${answers[index]}</em></li>
                `).join('')}
            </ul>

            <h2 style="color: #E74C3C;">Nhận xét:</h2>
            <p>${message}</p>

            <p class="footer">Generated by DoctorHub</p>
        `;
    }

    // Hàm xuất PDF
    function exportPDF() {
        const element = document.getElementById('pdf-content');

        const opt = {
            margin: 0.5,
            filename: 'ketqua-tramcam.pdf',
            image: {
                type: 'jpeg',
                quality: 0.98
            },
            html2canvas: {
                scale: 2
            },
            jsPDF: {
                unit: 'in',
                format: 'a4',
                orientation: 'portrait'
            }
        };

        html2pdf().from(element).set(opt).save();
    }

    // Tự động gọi khi vào trang (test thử)
    calculateResult();
    </script>

    <!-- Nội dung ẩn dùng để xuất PDF -->
    <div id="pdf-content"></div>

</body>

</html>